#!/usr/bin/env bash
set -e

mkdir -p /lib/systemd/system/sysinit.target.wants
ln -s ../createhs.service /lib/systemd/system/sysinit.target.wants/createhs.service
systemctl daemon-reload

if [ -e /disable-root-fs ]; then
	mv disable-root-fs disable-root-fs.wait
fi

# Are we being instructed to abort?
#
if [ -f "/var/tmp/system-hostname.off" ]; then
	# Aborting, but cleanup first
	#
	rm "/var/tmp/system-hostname.off"
else
	# Reset hostname on first boot
	#
	touch /var/tmp/system-hostname
fi

# Update /etc/hosts on first boot
#
touch /var/tmp/system-hosts
